name: CI

on:
  push:
    branches: 
      - main
      - jenk
  workflow_dispatch:

jobs:
  my-first-job:
    runs-on: ubuntu-latest
        
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          ref: jenk

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Check Java version
        run: java -version

      - name: show dir
        run: pwd

      - name: list file
        run: ls -al

      - name: install depend
        run: mvn compile

      - name: build
        run: mvn package -DskipTests

      - name: test
        run: mvn test
